version: '3'
services:
  db:
    container_name: mysql
    build: .
    image: edmitry/mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - .:/app
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app
volumes:
  socks:
  mysql_data:
    external: true
